doctrine:
    orm:
        mappings:
            DataMinerBundle:
                mapping: true
                type: xml
                dir: 'Resources/config/doctrine'
                is_bundle: true
                alias: 'DataMiner'
                prefix: 'DataMiner\Model'
