services:
  data_miner.property.base:
    class: PhpDataMiner\Model\Property\Property
    parent: data_miner.property.abstract
    tags:
      - { name: data_miner.property }

  data_miner.property.float:
    class: PhpDataMiner\Model\Property\FloatProperty
    parent: data_miner.property.abstract
    tags:
      - { name: data_miner.property }

  data_miner.property.int:
    class: PhpDataMiner\Model\Property\IntegerProperty
    parent: data_miner.property.abstract
    tags:
      - { name: data_miner.property }

  data_miner.property.date:
    class: PhpDataMiner\Model\Property\DateProperty
    parent: data_miner.property.abstract
    tags:
      - { name: data_miner.property }
