imports:
  - { resource: "properties.yml" }
  - { resource: "features.yml" }
  - { resource: "filters.yml" }

services:
  data_miner.command:
    class: DataMiner\Command\TrainCommand
    autowire: true
    tags:
      - {name: console.command}

  DataMiner\Miner\DefaultKernel: "@data_miner.kernel.default"
  data_miner.kernel.default:
    class: DataMiner\Miner\DefaultKernel

  DataMiner\Miner\Miner: "@data_miner.miner"
  data_miner.miner:
    class: DataMiner\Miner\Miner
    autowire: true
    arguments:
      - "@data_miner.property.provider"
      - [ "@data_miner.filter.colon", "@data_miner.filter.section",  "@data_miner.filter.word_tree"]
      - []

  data_miner.property.provider:
    class: PhpDataMiner\Model\Property\Provider
    arguments:
      - "@data_miner.property.registry"

  data_miner.property.registry:
    class: DataMiner\Property\Registry

